name: Run Selftests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unit tests
      run: |
        python run_selftests.py --categories unit
    
    - name: Run core feature tests
      run: |
        python run_selftests.py --core
      
    - name: Generate test report
      run: |
        python run_selftests.py --all --report test-report.json
      continue-on-error: true
    
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: test-report.json
      if: always()
